### ISSUE TITLE
Something Wrong

### ISSUE THREAD

**Issue by charlesfufu** [ShomyLiu/pytorch-pcnn#1]
![image](https://user-images.githubusercontent.com/33311822/46992647-ad916f80-d13d-11e8-86fb-d58b80e8c6d2.png)

**Comment by ShomyLiu** [comment]
Hi, `file` is only in Python 2.7X, and your python version is 3.6.  You can try replace `file` into `open`

**Comment by charlesfufu** [comment]
> Hi, `file` is only in Python 2.7X, and your python version is 3.6. You can try replace `file` into `open`

![image](https://user-images.githubusercontent.com/33311822/46993641-cf412580-d142-11e8-9934-9ca22ca34d79.png)
How about this one?

**Comment by ShomyLiu** [comment]
The training phase should be in this way in the terminal:
```
python main_sem.py  train
```
If you run code in IDE (e.g., Pycharm) , You can modify the `__main__` function with:
```
if __name__ == "__main__":
     train()
```

**Comment by charlesfufu** [comment]
> The training phase should be in this way in the terminal:
> 
> ```
> python main_sem.py  train
> ```
> If you run code in IDE (e.g., Pycharm) , You can modify the `__main__` function with:
> 
> ```
> if __name__ == "__main__":
>      train()
> ```

According to what you say, get the same result.

**Comment by ShomyLiu** [comment]
The normal output of main_sem should be:
![image](https://user-images.githubusercontent.com/10215945/46995535-bd17b500-d14b-11e8-9802-19654b341610.png)

Maybe the environment difference?

**Comment by charlesfufu** [comment]
def train(**kwargs):
![image](https://user-images.githubusercontent.com/33311822/46996456-44b2f300-d14f-11e8-8137-c3804ac65d09.png)
Where is the value of the parameter?

**Comment by charlesfufu** [comment]
> The normal output of main_sem should be:
> ![image](https://user-images.githubusercontent.com/10215945/46995535-bd17b500-d14b-11e8-9802-19654b341610.png)
> 
> Maybe the environment difference?

Maybe you should upgrade your program with python3

**Comment by charlesfufu** [comment]
> > The normal output of main_sem should be:
> > ![image](https://user-images.githubusercontent.com/10215945/46995535-bd17b500-d14b-11e8-9802-19654b341610.png)
> > Maybe the environment difference?
> 
> Maybe you should upgrade your program with python3

![image](https://user-images.githubusercontent.com/33311822/46996828-898b5980-d150-11e8-9837-30eed3bb889e.png)
I don't know if you write program like these *** if __name__ == "__main__":  train()***,how to pass in the value at def train(**kwargs) function ?

**Comment by ShomyLiu** [comment]
OK, I will update my code with Python3.X.
You can change `config.py` Line 66: 
````
.iteritems()   ->   .items()
```
Maybe there will be other codes different from python2.x and 3.x

**Comment by charlesfufu** [comment]
> OK, I will update my code with Python3.X.
> You can change `config.py` Line 66:
> 
> ```
> .iteritems()   ->   .items()
> ```
> Maybe there will be other codes different from python2.x and 3.x
> ```

Yes, I had found at least four difference between python2  and  python3. Looking forward to your code with python3. Thanks! !

**Comment by ShomyLiu** [comment]
Yes, I'm trying to update with python3. And I think it would be better with Pytorch 0.4 or later in the revision.

**Comment by charlesfufu** [comment]
> > > The normal output of main_sem should be:
> > > ![image](https://user-images.githubusercontent.com/10215945/46995535-bd17b500-d14b-11e8-9802-19654b341610.png)
> > > Maybe the environment difference?
> > 
> > 
> > Maybe you should upgrade your program with python3
> 
> ![image](https://user-images.githubusercontent.com/33311822/46996828-898b5980-d150-11e8-9837-30eed3bb889e.png)
> I don't know if you write program like these *** if **name** == "**main**": train()***,how to pass in the value at def train(**kwargs) function ?

![image](https://user-images.githubusercontent.com/33311822/47003936-04f60680-d163-11e8-86bd-29ae71257816.png)
I can not run the part program of picture. Do you know what's reason causes these? my pytorch version is 0.4

**Comment by ShomyLiu** [comment]
Yeah. My code is in Pytorch0.3. I'm updating code into Python3.x and Pytorch 0.4

**Comment by ShomyLiu** [comment]
@charlesfufu  The code has updated. the master branch is under Python 3.5x and Pytorch 0.4+.

**Comment by charlesfufu** [comment]
> @charlesfufu The code has updated. the master branch is under Python 3.5x and Pytorch 0.4+.

Wonderful !!

**Comment by charlesfufu** [comment]
> > @charlesfufu The code has updated. the master branch is under Python 3.5x and Pytorch 0.4+.
> 
> Wonderful !!

![image](https://user-images.githubusercontent.com/33311822/47010165-d97a1880-d170-11e8-96d0-c34c265bba37.png)
Do you know why?

**Comment by Wangpeiyi9979** [comment]
try changing the "use_gpu" in config.py to False.

**Comment by charlesfufu** [comment]
> try changing the "use_gpu" in config.py to False.

still wrong

**Comment by Wangpeiyi9979** [comment]
Is the same wrong message?

**Comment by charlesfufu** [comment]
> Is the same wrong message?

yeah！！Maybe is not  GPU problem.

**Comment by Wangpeiyi9979** [comment]
![image](https://user-images.githubusercontent.com/42565075/47012903-0aaa1700-d178-11e8-8ac1-52a46718f9ad.png)
try changing the codes here to this

**Comment by charlesfufu** [comment]
> ![image](https://user-images.githubusercontent.com/42565075/47012903-0aaa1700-d178-11e8-8ac1-52a46718f9ad.png)
> try changing the codes here to this

![image](https://user-images.githubusercontent.com/33311822/47013698-b05e8580-d17a-11e8-9d4c-2f6367d061c9.png)
No,that's wrong.

**Comment by Wangpeiyi9979** [comment]
![image](https://user-images.githubusercontent.com/42565075/47013899-485c6f00-d17b-11e8-8d71-de09486f8045.png)
this?

**Comment by Wangpeiyi9979** [comment]
![image](https://user-images.githubusercontent.com/42565075/47014106-d8021d80-d17b-11e8-9d0d-6a391e56b718.png)
also change the code here, and add long(). it may work

**Comment by charlesfufu** [comment]
![image](https://user-images.githubusercontent.com/33311822/47014286-5c54a080-d17c-11e8-9bd3-36c0f8761cc5.png)

No, not right
Can I ask you about it, have you run it since the program was modified?

**Comment by Wangpeiyi9979** [comment]
![image](https://user-images.githubusercontent.com/42565075/47014357-a178d280-d17c-11e8-86ef-835de9ebe42b.png)

**Comment by charlesfufu** [comment]
@Wangpeiyi9979  what about win10 ?

**Comment by Wangpeiyi9979** [comment]
> @Wangpeiyi9979 what about win10 ?
it should work. changing the code here, add long()..
![image](https://user-images.githubusercontent.com/42565075/47014734-b013b980-d17d-11e8-80b3-01538d81e0a5.png)

and here
![image](https://user-images.githubusercontent.com/42565075/47014877-100a6000-d17e-11e8-9439-d815025d5f5b.png)

**Comment by charlesfufu** [comment]
@ShomyLiu

**Comment by ShomyLiu** [comment]
@charlesfufu   I have reviewed code carefully and cannot reproduce your problems either in GPU or CPU.
Please check your environments.  
My environments are listed here:
```
- OS: Ubuntu 16.04 
- Python: 3.5
- Pytorch: 0.4.1
- GPU: NVIDIA GTX 1080Ti with 387.34 drivers.
```

**Comment by charlesfufu** [comment]
Have you tested your program on windows?I think maybe is the operating system problem

**Comment by charlesfufu** [comment]
![image](https://user-images.githubusercontent.com/33311822/47059341-90bb7180-d1fb-11e8-8d34-52d78d9ff84d.png)
I had found the bug 

> @charlesfufu I have reviewed code carefully and cannot reproduce your problems either in GPU or CPU.
> Please check your environments.
> My environments are listed here:
> 
> ```
> - OS: Ubuntu 16.04 
> - Python: 3.5
> - Pytorch: 0.4.1
> - GPU: NVIDIA GTX 1080Ti with 387.34 drivers.
> ```

![image](https://user-images.githubusercontent.com/33311822/47059368-a761c880-d1fb-11e8-8ee0-f8ae5146d60a.png)
I had found the bug ! !

**Comment by ShomyLiu** [comment]
OK, It seems strange.  It would be nice If the issue has been solved.  If necessary, you can create a pull request.
Thanks.

**Comment by ghost** [comment]
> ![image](https://user-images.githubusercontent.com/33311822/47059341-90bb7180-d1fb-11e8-8d34-52d78d9ff84d.png)
> I had found the bug
> 
> > @charlesfufu I have reviewed code carefully and cannot reproduce your problems either in GPU or CPU.
> > Please check your environments.
> > My environments are listed here:
> > ```
> > - OS: Ubuntu 16.04 
> > - Python: 3.5
> > - Pytorch: 0.4.1
> > - GPU: NVIDIA GTX 1080Ti with 387.34 drivers.
> > ```
> 
> ![image](https://user-images.githubusercontent.com/33311822/47059368-a761c880-d1fb-11e8-8ee0-f8ae5146d60a.png)
> I had found the bug ! !
![image](https://user-images.githubusercontent.com/37874490/49714691-dab75580-fc88-11e8-9366-14d1e412e07b.png)


你好，我遇到和你一样的报错信息【上图】，但没找到应该在哪里修改这个bug。看起来是pytorch在对数据类型进行转换的时候出现的问题，请问你是如何解决的呢？最后整个模型可以跑起来了吗？

**Comment by XAKK** [comment]
> ![image](https://user-images.githubusercontent.com/33311822/47059341-90bb7180-d1fb-11e8-8d34-52d78d9ff84d.png)
> I had found the bug
> 
> > @charlesfufu I have reviewed code carefully and cannot reproduce your problems either in GPU or CPU.
> > Please check your environments.
> > My environments are listed here:
> > ```
> > - OS: Ubuntu 16.04 
> > - Python: 3.5
> > - Pytorch: 0.4.1
> > - GPU: NVIDIA GTX 1080Ti with 387.34 drivers.
> > ```
> 
> ![image](https://user-images.githubusercontent.com/33311822/47059368-a761c880-d1fb-11e8-8ee0-f8ae5146d60a.png)
> I had found the bug ! !

Can you show the details about fixing this bug?

**Comment by ShomyLiu** [comment]
@XAKK  
Hi, could you please show what's the problem here?
I have checked the codes and run successfully right now under the following environment:

- Ubuntu 18.04
- Python 3.X
- Pytorch 0.4+ (1.0 is ok)

**Comment by XAKK** [comment]
@ShomyLiu 
Hi, I have the same problem as @charlesfufu 
it seems that this problem only appear on the Windows.

Traceback (most recent call last):
  File "main_sem.py", line 123, in <module>
    fire.Fire()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main_sem.py", line 64, in train
    out = model(data[:-1])
  File "C:\Users\79052\AppData\Roaming\Python\Python36\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\SFOH\pytorch-pcnn-master\models\PCNN.py", line 72, in forward
    lexical_level_emb = self.word_embs(lexical_feature)  # (batch_size, 6, word_dim
  File "C:\Users\79052\AppData\Roaming\Python\Python36\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\79052\AppData\Roaming\Python\Python36\site-packages\torch\nn\modules\sparse.py", line 118, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\Users\79052\AppData\Roaming\Python\Python36\site-packages\torch\nn\functional.py", line 1454, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)

**Comment by ShomyLiu** [comment]
@XAKK 
I will reproduce the problem in Windows platform as soon as possible and find out the solution.

**Comment by XAKK** [comment]
I think I found a problem solving strategy for Windows platform.
I modified the codes for three places, and run successfully on

- Windows 10

- Python 3.6

- Pytorch 1.0

Here are the changes:
main_sem.py
line 65:
`            loss = criterion(out, data[-1])`
↓
`            out1 = out.type(torch.cuda.FloatTensor)
            data1 = data[-1].type(torch.cuda.LongTensor)
            loss = criterion(out1, data1)`

line 92 - 95:
`         if opt.use_gpu:
            data = list(map(lambda x: torch.LongTensor(x).cuda(), data))
        else:
            data = list(map(lambda x: torch.LongTensor(x), data))`
↓

`        if opt.use_gpu:
            # data = list(torch.cuda.LongTensor(long(i)) for i in data)
            data = list(map(lambda x: torch.LongTensor(x.long()).cuda(), data))
        else:
            data = list(map(lambda x: torch.LongTensor(x.long()), data))`

PCNN.py line 68:
`lexical_feature, word_feautre, left_pf, right_pf = x`
↓
`        lexical_feature, word_feautre, left_pf, right_pf = x
        lexical_feature = lexical_feature.type(torch.cuda.LongTensor)
        word_feautre = word_feautre.type(torch.cuda.LongTensor)
        left_pf =left_pf.type(torch.cuda.LongTensor)
        right_pf = right_pf.type(torch.cuda.LongTensor)`

### This is part of my result with defualt setting
<<< (9+1)-WAY EVALUATION TAKING DIRECTIONALITY INTO ACCOUNT -- OFFICIAL >>>:
Micro-averaged result (excluding Other):
P = 1907/2409 =  79.16%     R = 1907/2263 =  84.27%     F1 =  81.64%

MACRO-averaged result (excluding Other):
P =  78.58%	R =  83.26%	F1 =  80.77%
Thank you! @ShomyLiu

**Comment by ShomyLiu** [comment]
@XAKK  Thanks for the note.
I will refine the codes for windows recently.
It seems that the code above can be simplified with:
```
 out.type(torch.cuda.FloatTensor) -> out.float()
...

lexical_feature.type(torch.cuda.LongTensor) -> lexical_feature.long()
```

**Comment by Xin-Deng** [comment]
![image](https://user-images.githubusercontent.com/48913404/60975543-bc205680-a35e-11e9-9df9-2ba138e0a2c8.png)
我并没有修改任何东西 目录下的确有该文件 为什么会找不到呢？

**Comment by ShomyLiu** [comment]
@learning-makes-me-happy-a  请确认下执行命令所在的目录。 需要在主目录，而不是说dataset下

**Comment by Xin-Deng** [comment]
> @learning-makes-me-happy-a 请确认下执行命令所在的目录。 需要在主目录，而不是说dataset下

thanks  I have solved this problem

**Comment by maxuejie514** [comment]
不知道怎么运行.sh的那个文件，现在只得到了acc,,可不可以告知一下，谢谢
